name: create repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'set repo prefix'
        required: true
        default: 'service'
        type: choice
        options:
          - example
          - service
      name:
        description: 'set repo name'
        required: true
        default: 'github-actions'
        type: string

jobs:
  auto-create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: create-repo
        id: create_repo
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
#          gh repo create --public ${{ inputs.prefix }}-${{ inputs.name }}
          exit 1
      - name: slack
        if: always()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "outcome": "레포지토리 생성 상태 : ${{steps.create_repo.conclusion }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
