name: create repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'set repo prefix'
        required: true
        default: 'service'
        type: choice
        options:
          - example
          - service
      name:
        description: 'set repo name'
        required: true
        default: 'github-actions'
        type: string

jobs:
  create-repo-auto:
    runs-on: ubuntu-latest
    steps:
      - name: create-repo
        id: create-repo
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          gh repo create --public --add-readme hangjin-action/${{ inputs.prefix }}-${{ inputs.name }}
      - name: slack
        if: always()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "attachments" : [
                {
                  "pretext": "create repo result",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "create repo result ${{steps.create-repo.outcome }}",
                      "short": true,
                      "value": "${{ inputs.prefix }}-${{ inputs.name }}"  
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
