name: debug
on: push

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: force fail
        run: cat test.txt
      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 5