name: git test
on:
  push:
    branches: ['dev', 'prod']

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: echo
        run: |
          echo ${{ vars.level }}