name: if-condition 2
on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: exit 1
        run: exit 1
      - name: echo hello
        if: always()
        run: echo hello

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: always()
    steps:
      - name: echo hello
        run: echo hello
