# output
# 동일한 job의 step, 다른 job과 데이터 공유
# 파일 기반의 데이터를 공유할시에는 artifact를 사용
# output은 단순한 값 전달할때 사용하고
# key - value 형태로 데이터를 저장

name: output
on: push

jobs:
  create-output:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ secrets.TEST_JSON }}
    steps:
      - name: echo output
        id: check-output
        run: |
          echo "test=hello" >> $GITHUB_OUTPUT
      - name: check output
        run: |
          echo ${{ steps.check-output.outputs.test }}
          
  get-output:
    runs-on: ubuntu-latest
    needs: create-output
    steps:
      - name: get output
        run: echo ${{ needs.create-output.outputs.test }}