name: push-workflow
on: push

jobs:
  push-job: # push-job이라는 이름의 job
    runs-on: ubuntu-latest # push-job이 우분투에서 실행된다는 의미이다.
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github actions
