name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'set name'
        required: true
        default: 'github-actions'
        type: string
      environment:
        description: 'set env'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2 echo github action
        run: |
          echo hello world
          echo github actions!
      - name: echo inputs
        run: |
          echo "Name: ${{inputs.name}}"
          echo "Environmnet: ${{inputs.environment}}"